body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please include a summary of the change and which issue is fixed. Please also have relevant motivation and context. Could you list any dependencies that are required for this change?
      placeholder: Fixes # (issue)
  - type: checkboxes
    attributes:
    label: Type of change
    description: Please delete options that are not relevant.
    options:
      - label: Bug fix (non-breaking change which fixes an issue)
      - label: New feature (non-breaking change which adds functionality)
      - label: Breaking change (fix or feature that would cause existing functionality not to work as expected)
      - label: This change requires a documentation update
  - type: textarea
    id: test
    attributes:
      label: How Has This Been Tested?
      description: Please describe the tests that you ran to verify your changes. Could you provide instructions so we can reproduce them? Please also list any relevant details for your test configuration.
      placeholder: |
        - [ ] Test A
        - [ ] Test B
  - type: markdown
    attributes:
      label: checklist
      description: check this list before opening a PR
      value: |
        - [ ] My code follows the style guidelines of this project
        - [ ] I have performed a self-review of my code
        - [ ] I have commented on my code, particularly in hard-to-understand areas
        - [ ] I have made corresponding changes to the documentation
        - [ ] My changes generate no new warnings
        - [ ] I have added tests that prove my fix is effective or that my feature works
        - [ ] New and existing unit tests pass locally with my changes
        - [ ] Any dependent changes have been merged and published in downstream modules
